title: Hiresense Handoff API
description: Docs for Mobius's integration with Hiresense's AI-run interview handoff API.
version: "1.4.1"
updated: "2026-10-01 08:14 UTC"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
